version: '2'
services:
  web:
    build: .
    ports:
     - "8080:80"
     - "443:443"
    depends_on:
     - redis-master
  redis-master:
    image: redis
    ports:
     - "6379:6379"
  redis-slave:
    image: kubernetes/redis-slave:v2@sha256:926e24d56c43b896f10a5e460c713effe6cd29cc84e3c51829ae44cb9740bbf3
    depends_on:
     - redis-master
