version: '2'
services:
  web:
    build: .
    ports:
     - "8080:80"
     - "443:443"
    depends_on:
     - redis-master
  redis-master:
    image: redis:2.8.23
    ports:
     - "6379:6379"
  redis-slave:
    image: kubernetes/redis-slave:v2
    depends_on:
     - redis-master
